name: tapem
description: "Tap’em – NFC-basiertes Gym-Tracking und Gym-Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  
  # State management
  provider: ^6.0.5

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # Persistence & Utilities
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  url_launcher: ^6.1.7

  # UI & Visualization
  fl_chart: ^0.70.0
  table_calendar: ^3.0.8
  flutter_staggered_grid_view: ^0.6.2

  # NFC
  nfc_manager: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation for serializable models
  build_runner: ^2.4.6
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
