name: tapem
description: "Tap’em – NFC-basiertes Gym-Tracking und Gym-Management"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Utilities
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  uuid: ^3.0.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.2.3
  fl_chart: ^0.70.0
  flutter_staggered_grid_view: ^0.6.2
  table_calendar: ^3.0.8

  # Utilities
  flutter_dotenv: ^5.0.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  url_launcher: ^6.1.7

  # NFC
  # nfc_manager: ^3.5.0
  # flutter_nfc_kit: ^3.0.1

  # Persistence
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/logos/
