name: gymapp
description: Gym Progress Tracking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.1.1
  fl_chart: ^0.70.0
  table_calendar: ^3.0.8
  nfc_manager: ^3.5.0
  url_launcher: ^6.1.7
  intl: ^0.20.2
  flutter_staggered_grid_view: ^0.6.2


  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2

  # State management
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
